name: Checks

on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install aspell (spell checker)
      run: |
        sudo apt-get install aspell aspell-en

    - name: Run spell checker
      run: |
        inv spellcheck